language: scala
sbt_args: -Xmx2048M
before_script: ./make_credentials.sh
script: sbt test

# If building master, Publish to Sonatype and trigger builds
after_success:
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && sbt publish"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-highcharts"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-vtd"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-maven"
  - "[[ $TRAVIS_PULL_REQUEST == \"false\" ]] && ./trigger_build.py gatling/gatling-sbt"

sudo: false

# whitelist
branches:
  only:
    - master
